### ISSUE TITLE
Editing a Voice

### ISSUE THREAD

**Issue by AntonyBearpark** [mattvv/lineplease#65] opened 2012-09-27 13:04 UTC
When I try to edit a voice (from female to male/male to female) it doesn't save, on bother the iOS app and on the web browser.

**Comment by mattvv** [comment] 2012-10-15 18:05
Hi @AntonyBearpark - Sorry for the delay getting back to this I didn't see this.

What version of iOS are you running?

**Comment by bugpybear** [comment] 2012-10-15 18:07
6.0

Antony Bearpark
http://antonybearpark.co.uk/

**Comment by mattvv** [comment] 2012-10-15 18:10
Thanks for the speedy Reply - Can you send a message to matt@lineplea.se with your username so I can take a look what the issue is. Thanks!

**Comment by CharityF** [comment] 2013-01-19 21:26
I'm actually having the same problem... I accidently put a line in as female but it was actually a male speaking and I have been trying to change it but it won't save the change for some reason...

**Comment by mattvv** [comment] 2013-12-04 22:10
This issue is fixed in the new iOS version released today

**Closed as completed by mattvv** 2013-12-04 22:10 UTC
